# Generated by Django 2.1.7 on 2019-03-29 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=200, null=True, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Local')),
                ('ubicacion_local', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicacion del Local')),
                ('imagen_muestra', models.ImageField(blank=True, default='core/sin_imagen.jpg', null=True, upload_to='vendedor/img_tiendas/', verbose_name='Imagen de muestra')),
                ('imagen_banner', models.ImageField(blank=True, default='core/sin_imagen.jpg', null=True, upload_to='vendedor/img_tiendas/', verbose_name='Imagen de Banner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'ordering': ['nombre_local'],
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Oferta')),
                ('tipo_oferta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Oferta')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.Local')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'ordering': ['tipo_oferta'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('precio', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio')),
                ('oferta', models.BooleanField(blank=True, default=False, null=True, verbose_name='Producto en Oferta')),
                ('precio_oferta', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio de la Oferta')),
                ('stock', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Stock del Producto')),
                ('imagen', models.ImageField(blank=True, default='core/sin_imagen.jpg', null=True, upload_to='vendedor/img_productos/')),
                ('cambios_restantes', models.PositiveIntegerField(blank=True, default=3, null=True, verbose_name='Cambios restantes de precios')),
                ('activado', models.BooleanField(blank=True, default=True, null=True, verbose_name='Producto activado?')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.Categoria_Productos')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['oferta', 'precio', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total de puntos')),
                ('tipo_cuenta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de cuenta')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.Local')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Puntos',
                'verbose_name_plural': 'Puntos',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidad de Medida')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medidas',
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendedor.Unidad_Medida'),
        ),
        migrations.AddField(
            model_name='productos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
