# Generated by Django 2.1.7 on 2019-03-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad_medida',
            name='medida',
        ),
        migrations.AddField(
            model_name='unidad_medida',
            name='medida_plural',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidad de Medida Plural'),
        ),
        migrations.AddField(
            model_name='unidad_medida',
            name='medida_unidad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unidad de Medida Unidad'),
        ),
    ]
