# Generated by Django 2.1.7 on 2019-04-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0006_oferta_activado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['precio', 'oferta', 'nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
