# Generated by Django 2.1.7 on 2019-04-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0007_auto_20190407_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['oferta', 'precio', 'nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterField(
            model_name='local',
            name='imagen_banner',
            field=models.ImageField(blank=True, default='vendedor/Mi_Tienda.png', null=True, upload_to='vendedor/img_tiendas/', verbose_name='Imagen de Banner'),
        ),
    ]
