# Generated by Django 2.1.7 on 2019-04-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0008_auto_20190419_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='activado',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Local activado?'),
        ),
    ]
