# Generated by Django 2.1.7 on 2019-04-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0009_local_activado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.CharField(blank=True, choices=[('general', 'general'), ('temporada', 'temporada'), ('rango_cliente', 'rango_cliente'), ('convencional', 'convencional')], max_length=200, null=True, verbose_name='Tipo de Oferta'),
        ),
    ]
