# Generated by Django 2.1.7 on 2019-05-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0010_auto_20190427_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.CharField(blank=True, choices=[('general', 'Oferta General'), ('temporada', 'Oferta de Temporada'), ('rango_plata', 'Oferta para clientes de rango plata'), ('rango_oro', 'Oferta para clientes de rango oro'), ('rango_diamante', 'Oferta para clientes de rango diamante'), ('convencional', 'Oferta Convencional')], max_length=200, null=True, verbose_name='Tipo de Oferta'),
        ),
    ]
