# Generated by Django 2.1.7 on 2019-05-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0012_auto_20190514_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='maximo_prod_comprar',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Maximo de productos a comprar'),
        ),
    ]
