# Generated by Django 2.1.7 on 2019-06-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0013_productos_maximo_prod_comprar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='cambios_restantes',
        ),
    ]
