# Generated by Django 2.1.7 on 2019-06-17 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendedor', '0014_remove_productos_cambios_restantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_auditoria_productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ID Producto')),
                ('nombre_producto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Producto')),
                ('accion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Accion')),
                ('fecha_registro', models.DateField(blank=True, null=True, verbose_name='Fecha de registro')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de Productos',
                'verbose_name_plural': 'Auditoria de Productos',
            },
        ),
    ]
