# Generated by Django 2.1.7 on 2019-07-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedor', '0015_registro_auditoria_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_productos',
            name='categoria',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='local',
            name='nombre_local',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Local'),
        ),
        migrations.AlterField(
            model_name='local',
            name='ubicacion_local',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicacion del Local'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='oferta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.CharField(blank=True, choices=[('general', 'Oferta General'), ('temporada', 'Oferta de Temporada'), ('rango_plata', 'Oferta para clientes de rango plata'), ('rango_oro', 'Oferta para clientes de rango oro'), ('rango_diamante', 'Oferta para clientes de rango diamante'), ('convencional', 'Oferta Convencional')], max_length=30, null=True, verbose_name='Tipo de Oferta'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='puntos',
            name='tipo_cuenta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de cuenta'),
        ),
        migrations.AlterField(
            model_name='registro_auditoria_productos',
            name='accion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Accion'),
        ),
        migrations.AlterField(
            model_name='unidad_medida',
            name='medida_plural',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidad de Medida Plural'),
        ),
        migrations.AlterField(
            model_name='unidad_medida',
            name='medida_unidad',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidad de Medida Unidad'),
        ),
    ]
