# Generated by Django 2.1.7 on 2019-03-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_usuarios',
            name='tipo_premium',
            field=models.PositiveIntegerField(blank=True, choices=[('0', 'sin premium'), ('1', 'premium nivel 1'), ('2', 'premium nivel 2'), ('3', 'premium nivel 3')], default=0, null=True, verbose_name='Tipo de Premium'),
        ),
        migrations.AlterField(
            model_name='tipo_usuarios',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('administrador', 'administrador'), ('vendedor', 'vendedor'), ('cliente', 'cliente')], default='cliente', max_length=200, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
