# Generated by Django 2.1.7 on 2019-03-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190325_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_usuarios',
            name='tipo_premium',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'sin premium'), (1, 'premium nivel 1'), (2, 'premium nivel 2'), (3, 'premium nivel 3')], default=0, null=True, verbose_name='Tipo de Premium'),
        ),
    ]
