# Generated by Django 2.1.7 on 2019-06-27 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0004_tipo_usuarios_fecha_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Acceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de Registro')),
                ('tipo_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acceso',
                'verbose_name_plural': 'Log de Accesos',
            },
        ),
    ]
