# Generated by Django 2.1.7 on 2019-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_log_acceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preguntas_secretas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pregunta Secreta')),
            ],
            options={
                'verbose_name': 'Preguntas secretas',
                'verbose_name_plural': 'Preguntas secretas',
            },
        ),
    ]
