# Generated by Django 2.1.7 on 2019-06-29 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0006_preguntas_secretas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_respuesta_secreta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Respuesta Secreta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Preguntas_secretas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tabla de Preguntas y Respuestas',
                'verbose_name_plural': 'Tabla de Preguntas y Respuestas',
            },
        ),
    ]
