# Generated by Django 2.1.7 on 2019-07-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_login_respuesta_secreta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_acceso',
            name='fecha_registro',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='log_acceso',
            name='tipo_cliente',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='login_respuesta_secreta',
            name='respuesta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Respuesta Secreta'),
        ),
        migrations.AlterField(
            model_name='preguntas_secretas',
            name='pregunta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pregunta Secreta'),
        ),
        migrations.AlterField(
            model_name='tipo_usuarios',
            name='tipo_usuario',
            field=models.CharField(blank=True, choices=[('administrador', 'administrador'), ('vendedor', 'vendedor'), ('cliente', 'cliente')], default='cliente', max_length=20, null=True, verbose_name='Tipo de Usuario'),
        ),
    ]
