# Generated by Django 2.1.7 on 2019-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_registro_listas_registro_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='listas',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creacion de la lista'),
        ),
    ]
