# Generated by Django 2.1.7 on 2019-05-15 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0005_listas_fecha_creacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listas',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Listas', 'verbose_name_plural': 'Listas'},
        ),
        migrations.AddField(
            model_name='listas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
