# Generated by Django 2.1.7 on 2019-05-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20190515_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listas',
            options={'verbose_name': 'Listas', 'verbose_name_plural': 'Listas'},
        ),
        migrations.RemoveField(
            model_name='listas',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='listas',
            name='fecha_actualizacion',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de actualizacion de la lista'),
        ),
        migrations.AlterField(
            model_name='listas',
            name='estado_lista',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada'), ('armando_pedido', 'Armando Pedido'), ('lista_retiro', 'Listo para retirar'), ('completada', 'Lista completada'), ('no_retirada', 'No retirada')], default='normal', max_length=200, null=True, verbose_name='Estado de la lista'),
        ),
        migrations.AlterField(
            model_name='listas',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la lista'),
        ),
    ]
