# Generated by Django 2.1.7 on 2019-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20190516_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listas',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualizacion de la lista'),
        ),
    ]
