# Generated by Django 2.1.7 on 2019-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_auto_20190519_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_listas',
            name='producto_marcado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Producto marcado'),
        ),
    ]
