# Generated by Django 2.1.7 on 2019-06-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_productos_listas_producto_marcado'),
    ]

    operations = [
        migrations.AddField(
            model_name='listas',
            name='cancelaciones',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, verbose_name='Veces restantes a cancelar la lista'),
        ),
    ]
