# Generated by Django 2.1.7 on 2019-06-02 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0011_listas_cancelaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_listas',
            name='rut_cliente',
        ),
        migrations.AddField(
            model_name='registro_listas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
