# Generated by Django 2.1.7 on 2019-06-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_listas_total_marcado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_de_productos',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='registro_de_productos',
            name='user',
        ),
        migrations.DeleteModel(
            name='Registro_de_productos',
        ),
    ]
