# Generated by Django 2.1.7 on 2019-06-06 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_tipo_usuarios_fecha_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0015_auto_20190606_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_premium', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Premium')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio del Premium')),
                ('fecha_caducidad', models.DateField(blank=True, null=True, verbose_name='Fecha de Caducidad del Premium')),
                ('id_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Tipo_usuarios')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de premium',
            },
        ),
    ]
