# Generated by Django 2.1.7 on 2019-06-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_registro_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_premium',
            name='tipo_premium',
        ),
        migrations.AddField(
            model_name='registro_premium',
            name='premium',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tipo de Premium'),
        ),
    ]
