# Generated by Django 2.1.7 on 2019-06-21 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_auto_20190616_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='listas',
            name='valorizacion',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Fue Valorizada?'),
        ),
    ]
