# Generated by Django 2.1.7 on 2019-06-21 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendedor', '0015_registro_auditoria_productos'),
        ('cliente', '0019_listas_valorizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valorizacion_pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ID lista')),
                ('puntuacion', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Puntuacion')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios del pedido')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendedor.Local')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valorizacion de Pedidos',
                'verbose_name_plural': 'Valorizacion de Pedidos',
            },
        ),
    ]
