# Generated by Django 2.1.7 on 2019-06-21 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendedor', '0015_registro_auditoria_productos'),
        ('cliente', '0020_valorizacion_pedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_listas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='ID lista')),
                ('nombre_lista', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la lista')),
                ('fecha_registro', models.DateField(blank=True, null=True, verbose_name='Fecha de registro')),
                ('total', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total del pedido')),
                ('cantidad_items', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de Items')),
                ('cantidad_productos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Total de productos')),
                ('estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado del pedido')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendedor.Local')),
            ],
            options={
                'verbose_name': 'Reporte de Pedidos',
                'verbose_name_plural': 'Reporte de Pedidos',
            },
        ),
        migrations.RemoveField(
            model_name='registro_listas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='registro_listas',
            name='lista',
        ),
        migrations.RemoveField(
            model_name='registro_listas',
            name='local',
        ),
        migrations.DeleteModel(
            name='Registro_listas',
        ),
    ]
