# Generated by Django 2.1.7 on 2019-06-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0022_productos_listas_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorizacion_pedidos',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
    ]
