# Generated by Django 2.1.7 on 2019-07-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0023_valorizacion_pedidos_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listas',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la lista'),
        ),
    ]
