# Generated by Django 2.1.7 on 2019-07-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_auto_20190630_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_listas',
            name='estado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado del pedido'),
        ),
        migrations.AlterField(
            model_name='reporte_listas',
            name='nombre_lista',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de la lista'),
        ),
        migrations.AlterField(
            model_name='reporte_productos',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Producto'),
        ),
    ]
